version: "3.2"

services:
  compendium-api:
    build:
      context: "."
      dockerfile: ${COMPENDIUM_DOCKERFILE}
      args:
        COMPENDIUM_API_PORT: ${COMPENDIUM_API_PORT}
        COMPENDIUM_API_CONFIG_FILE: ${COMPENDIUM_API_CONFIG_FILE}
    ports:
      - "${COMPENDIUM_API_HOST_PORT}:${COMPENDIUM_API_PORT}"
